/*
    Generated by Fivem Typescript Boilerplate by Whitigol#2122
*/
import type { ConfigD } from "../../types/config";
import axios from "axios";

const Config: ConfigD = JSON.parse(
    LoadResourceFile(GetCurrentResourceName(), "config.json")
);

async function VersionCheck() {
    await new Promise((r) => setTimeout(r, 1000));
    console.log("^4[Whitigol Tablet] ^5Checking for updates...^7");
    const latest = await axios.get(
        "https://api.github.com/repos/WhitigolProd/cad/releases/latest"
    );
    const current = GetResourceMetadata(GetCurrentResourceName(), "version", 0);

    if (latest.data.tag_name !== current) {
        console.log(
            `^4[Whitigol Tablet] ^3Your version of the tablet is out of date! Please update to ${latest.data.tag_name} at https://github.com/WhitigolProd/cad/releases/latest/download/tablet.zip^7`
        );
    } else {
        console.log("^4[Whitigol Tablet] ^2You are up to date!^7");
    }
}

VersionCheck();
