/*
    Generated by Fivem Typescript Boilerplate by Whitigol#2122
*/
import type { ConfigD } from "../../types/config";

const Config: ConfigD = JSON.parse(
    LoadResourceFile(GetCurrentResourceName(), "config.json")
);

export function ShowNotification(text: string) {
    SetNotificationTextEntry("STRING");
    AddTextComponentString(text);
    DrawNotification(false, false);
}
